name: CI

on:
  pull_request:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  check-nightly:
    name: 'Build & test on nightly'
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test

  check-stable:
    name: 'Build & test on stable'
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --no-default-features
    - name: Run tests
      run: cargo test --no-default-features
