name: CI

on:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  check-stable:
    name: 'Build & test'
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
